# Generated by Django 4.2 on 2024-07-03 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_date_booked_appointment_date_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="reason_for_visit",
            new_name="reason",
        ),
    ]
