# Generated by Django 4.2 on 2024-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_appointment_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
