# Generated by Django 4.2 on 2024-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_appointment_doctor_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
