# Generated by Django 4.2 on 2024-07-02 06:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_profiles", "0002_alter_doctor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
