# Generated by Django 4.2 on 2024-07-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_profiles", "0003_alter_doctor_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="specialty",
            new_name="speciality",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("file", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="doctor_profiles.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
                "abstract": False,
            },
        ),
    ]
