name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test with django test
        run: python manage.py python manage.py test
      - name: Lint with flake8
        run: flake8
