# Generated by Django 4.2 on 2024-07-02 06:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_profiles", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="media/profiles/documents/"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
