# Generated by Django 4.2 on 2024-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_profiles", "0003_alter_document_file_alter_patient_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
