# Generated by Django 4.2 on 2024-07-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient_profiles", "0004_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="patient_profiles.patient",
            ),
        ),
    ]
