# Generated by Django 4.2 on 2024-07-06 19:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("patient_profiles", "0005_alter_document_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
