# Generated by Django 4.2 on 2024-07-10 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient_profiles", "0007_patient_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="timezone",
        ),
    ]
